### ISSUE TITLE
Using a dom-repeat inside the grain-masonry not working

### ISSUE THREAD

**Issue by chwzr** [daKmoR/grain-masonry#2]
I am getting errors using a dom-repeat to fill the masonry. 
The functions to add elements are not called propperly when the dom-repeat stamps the items.

**Comment by daKmoR** [comment]
so what code are you using?

something like this?
```
<dom-bind>
  <template>
    <grain-masonry>
    <template is="dom-repeat" items="{{people}}">
      <article>{{item.name}}</article>
    </template>
    </grain-masonry>
  </template>
</dom-bind>
```

just so I have a proper use case to test it with...

**Comment by chwzr** [comment]
exactly. The console says 
"Uncaught TypeError: Cannot read property 'add' of undefined" 
so i guess the element is not propperly passed to the function which adds items

**Comment by daKmoR** [comment]
should be solved with https://github.com/daKmoR/grain-masonry/commit/dae3c585681f4d76c8325989c4e6f634050a7bc2 and released as [v0.8.2](https://github.com/daKmoR/grain-masonry/releases/tag/v0.8.2).

pls check and close this issue :)

**Comment by chwzr** [comment]
works great! thx!

**Comment by yairopro** [comment]
It doesn't seem to work for me...
See [this JSBin](http://jsbin.com/celemarige/1/edit?html,console,output).
