### ISSUE TITLE
Overlapped Elements

### ISSUE THREAD

**Issue by JGSolutions** [daKmoR/grain-masonry#4]
My container has images and of course they can be different sizes. Of course I am using width: 100% and height auto for images.

By reading the documentation in the imagesLoaded
`Unloaded images can throw off Masonry layouts and cause item elements to overlap. imagesLoaded resolves this issue. imagesLoaded is a separate script`

Url
https://masonry.desandro.com/layout.html. 

Does your component handle this extra script needed?

**Comment by daKmoR** [comment]
this element listens to onLoad event of images and calls the layout of masonry after every successful image load.
I guess that is something similar the imagesLoaded script does?

**Comment by JGSolutions** [comment]
It's not the same. Need to have that imagesLoaded script.

**Comment by JGSolutions** [comment]
the problem is that even if the layout() method is called but if the images are still not loaded because of some latency it will not render properly and still get over lapping

**Comment by daKmoR** [comment]
I think the solution in place (https://github.com/daKmoR/grain-masonry/blob/master/GrainMasonry.html#L78) is sufficient.

If you have a concrete reproduce able example where this fails I can take a a closer look.
